name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: 'Restore from cache and install vcpkg'
        uses: lukka/run-vcpkg@v4
        with:
          # latest vcpkg commit October 31, 2020 11:38 EDT
          vcpkgGitCommitId: e9ff3cd5a04cd0e8122ff56e9873985ff71aa3ca
          setupOnly: true

      - name: 'Install vcpkg packages'
        shell: bash
        run: ${VCPKG_ROOT}/vcpkg install --debug fmt
